/**
 * GENERATED — no editar a mano.
 * Fuente: apps/web/tokens/ (DTCG). Regenerar: pnpm tokens:build
 */

export const zedCssVars = {
  accent: "--zed-accent",
  accentActive: "--zed-accent-active",
  accentHover: "--zed-accent-hover",
  accentOn: "--zed-accent-on",
  accentSoft: "--zed-accent-soft",
  badgeDangerBorder: "--zed-badge-danger-border",
  badgeInfoBorder: "--zed-badge-info-border",
  badgeSuccessBorder: "--zed-badge-success-border",
  badgeWarningBorder: "--zed-badge-warning-border",
  bgCanvas: "--zed-bg-canvas",
  bgInverse: "--zed-bg-inverse",
  bgMuted: "--zed-bg-muted",
  bgRaised: "--zed-bg-raised",
  bgSubtle: "--zed-bg-subtle",
  borderDefault: "--zed-border-default",
  borderStrong: "--zed-border-strong",
  borderSubtle: "--zed-border-subtle",
  borderWidth: "--zed-border-width",
  bpLg: "--zed-bp-lg",
  bpMd: "--zed-bp-md",
  codeBg: "--zed-code-bg",
  codeFg: "--zed-code-fg",
  contentReadable: "--zed-content-readable",
  contentWide: "--zed-content-wide",
  danger: "--zed-danger",
  dangerHover: "--zed-danger-hover",
  dangerOnSoft: "--zed-danger-on-soft",
  dangerSoft: "--zed-danger-soft",
  easeStandard: "--zed-ease-standard",
  fgDefault: "--zed-fg-default",
  fgInverse: "--zed-fg-inverse",
  fgMuted: "--zed-fg-muted",
  fgStrong: "--zed-fg-strong",
  fgSubtle: "--zed-fg-subtle",
  focusRing: "--zed-focus-ring",
  focusWidth: "--zed-focus-width",
  fontMono: "--zed-font-mono",
  fontUi: "--zed-font-ui",
  info: "--zed-info",
  infoHover: "--zed-info-hover",
  infoOnSoft: "--zed-info-on-soft",
  infoSoft: "--zed-info-soft",
  leadingNormal: "--zed-leading-normal",
  leadingRelaxed: "--zed-leading-relaxed",
  leadingSnug: "--zed-leading-snug",
  leadingTight: "--zed-leading-tight",
  radiusLg: "--zed-radius-lg",
  radiusMd: "--zed-radius-md",
  radiusPill: "--zed-radius-pill",
  radiusSm: "--zed-radius-sm",
  radiusXl: "--zed-radius-xl",
  radiusXs: "--zed-radius-xs",
  selectionBg: "--zed-selection-bg",
  selectionFg: "--zed-selection-fg",
  shadowMd: "--zed-shadow-md",
  shadowSm: "--zed-shadow-sm",
  shadowXs: "--zed-shadow-xs",
  sidebarWidth: "--zed-sidebar-width",
  space1: "--zed-space-1",
  space10: "--zed-space-10",
  space12: "--zed-space-12",
  space16: "--zed-space-16",
  space2: "--zed-space-2",
  space20: "--zed-space-20",
  space24: "--zed-space-24",
  space3: "--zed-space-3",
  space4: "--zed-space-4",
  space5: "--zed-space-5",
  space6: "--zed-space-6",
  space8: "--zed-space-8",
  statusbarHeight: "--zed-statusbar-height",
  success: "--zed-success",
  successHover: "--zed-success-hover",
  successOnSoft: "--zed-success-on-soft",
  successSoft: "--zed-success-soft",
  targetMin: "--zed-target-min",
  text2xl: "--zed-text-2xl",
  text3xl: "--zed-text-3xl",
  textBase: "--zed-text-base",
  textLg: "--zed-text-lg",
  textMd: "--zed-text-md",
  textSm: "--zed-text-sm",
  textXl: "--zed-text-xl",
  textXs: "--zed-text-xs",
  topbarHeight: "--zed-topbar-height",
  transitionBase: "--zed-transition-base",
  transitionFast: "--zed-transition-fast",
  transitionSlow: "--zed-transition-slow",
  warning: "--zed-warning",
  warningHover: "--zed-warning-hover",
  warningOnSoft: "--zed-warning-on-soft",
  warningSoft: "--zed-warning-soft",
  weightBold: "--zed-weight-bold",
  weightMedium: "--zed-weight-medium",
  weightRegular: "--zed-weight-regular",
  weightSemibold: "--zed-weight-semibold",
  zDrawer: "--zed-z-drawer",
  zShell: "--zed-z-shell",
} as const;

export type ZedCssVar = (typeof zedCssVars)[keyof typeof zedCssVars];
export type ZedCssVarName = keyof typeof zedCssVars;

/** Hex generado desde OKLCH (theme-color / favicon). No es origen. */
export const themeColorHex = {
  light: "#fcfaf4",
  dark: "#070d18",
} as const;

/** Hex generado desde accent / accent-on (tema claro) para el favicon. */
export const faviconHex = {
  background: "#2369c6",
  foreground: "#fcfaf4",
} as const;
